name: prh
on: [pull_request]

jobs:
  prh:
    name: prh
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    # add PATH (see: https://github.com/reviewdog/reviewdog#github-actions)
    - name: setup-reviewdog
      run: |
        URL=https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh
        wget -O - -q ${URL} | sh -s
        # apk --update add Git
        # rm -rf /var/lib/apt/lists/*
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: |
        set -x
        npm install -g prh@5.4.4
        npm cache clean --force
        prh --rules .github/workflows/prh/prh-rule.yml --verify istio/istio-step-by-step/*.md > prh.log || EXIT_CODE=$?
        cat prh.log | bin/reviewdog -reporter=github-pr-review -diff='git --no-pager diff HEAD^' -efm='%f(%l,%c): %m' -name=prh
        cat prh.log
        exit ${EXIT_CODE}

      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}




